language: node_js

node_js:
  - 0.10

before_install:
  - sudo apt-get remove -y imagemagick
  - wget http://www.imagemagick.org/download/releases/ImageMagick-6.8.9-8.tar.gz
  - tar xf ImageMagick-6.8.9-8.tar.gz
  - cd ImageMagick*
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..

script:
  - npm test
